# Generated by Django 3.2.5 on 2021-07-17 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfupload',
            options={'ordering': ['upload_date']},
        ),
    ]
